log:
  debug: true
  log_level: DEBUG # from logging library

active_preset: obs_outside

presets:
  camera_inside:
    source: 0 # connected webcam
    close_view: true
  camera_outside:
    source: 0 # connected webcam
    close_view: false
  obs_inside:
    source: 2 # OBS webcam
    close_view: true
  obs_outside:
    source: 2 # OBS webcam
    close_view: false

preprocess:
  dilatation_size: 3
  dilatation_shape: MORPH_DILATE # from OpenCV library

variance:
  close:
    min: 2000
    max: 8000
  far:
    min: 100
    max: 2000

motionManager:
  motion_threshold: 100
  drop_cam_thresh: 3
  shift_cam_thresh: 5

tracker:
  model_path: 'yolov8n.pt'
  track_classes: [0] # people

timers:
  cam_reset_check_time: 3
  motion_check_time: 3
  drop_check_time: 10 # low value just for testing, much bigger value is advised
  gone_check_time: 3